"""Add projectadmin

Revision ID: 3b3a9aea8986
Revises: None
Create Date: 2013-11-15 15:39:40.802262

"""

# revision identifiers, used by Alembic.
revision = '3b3a9aea8986'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_admin')
    ### end Alembic commands ###
