"""add_product_real

Revision ID: 426f5fedf8ea
Revises: 48b88b2599f4
Create Date: 2014-12-12 15:48:02.578582

"""

# revision identifiers, used by Alembic.
revision = '426f5fedf8ea'
down_revision = '48b88b2599f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('bugzilla_product', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'bugzilla_product')
    ### end Alembic commands ###
