"""add product

Revision ID: 48b88b2599f4
Revises: 39d44fcf8e74
Create Date: 2014-12-12 15:28:42.086863

"""

# revision identifiers, used by Alembic.
revision = '48b88b2599f4'
down_revision = '39d44fcf8e74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
